# Test your FastAPI endpoints

GET http://localhost:8000/api/favourite
Accept: application/json

###

POST http://localhost:8000/api/favourite
Content-Type: application/json

{
    "name": "Belgium"
}

###

DELETE http://localhost:8000/api/favourite
Content-Type: application/json

{
    "name": "Belgium"
}
